name: Docker
on: [push, pull_request]

jobs:
  docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build docker image
      run: cd app_python && docker build . -t app_python

    - name: Tag
      run: docker tag app_python homa3030/app_python
    
    - name: Push
      run: docker push homa3030/app_python

    - name: App.py Linter
      run: flake8 app_python/app.py

    - - name: Test.py Linter
      run: flake8 app_python/test.py